// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package mock_vacancy_svc is a generated GoMock package.
package mock_vacancy_svc

import (
	context "context"
	vacancies "homework-7/internal/svc/vacancies"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockVacancyProcessor is a mock of VacancyProcessor interface.
type MockVacancyProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockVacancyProcessorMockRecorder
}

// MockVacancyProcessorMockRecorder is the mock recorder for MockVacancyProcessor.
type MockVacancyProcessorMockRecorder struct {
	mock *MockVacancyProcessor
}

// NewMockVacancyProcessor creates a new mock instance.
func NewMockVacancyProcessor(ctrl *gomock.Controller) *MockVacancyProcessor {
	mock := &MockVacancyProcessor{ctrl: ctrl}
	mock.recorder = &MockVacancyProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVacancyProcessor) EXPECT() *MockVacancyProcessorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVacancyProcessor) Create(ctx context.Context, createDTO vacancies.CreateVacancyDto) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, createDTO)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVacancyProcessorMockRecorder) Create(ctx, createDTO interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVacancyProcessor)(nil).Create), ctx, createDTO)
}

// Delete mocks base method.
func (m *MockVacancyProcessor) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVacancyProcessorMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVacancyProcessor)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockVacancyProcessor) GetAll(ctx context.Context) ([]*vacancies.Vacancy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*vacancies.Vacancy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockVacancyProcessorMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockVacancyProcessor)(nil).GetAll), ctx)
}

// GetById mocks base method.
func (m *MockVacancyProcessor) GetById(ctx context.Context, id string) (*vacancies.Vacancy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*vacancies.Vacancy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockVacancyProcessorMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockVacancyProcessor)(nil).GetById), ctx, id)
}

// Update mocks base method.
func (m *MockVacancyProcessor) Update(ctx context.Context, id string, dto vacancies.UpdateVacancyDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVacancyProcessorMockRecorder) Update(ctx, id, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVacancyProcessor)(nil).Update), ctx, id, dto)
}
